catalogs:
  framework:
    nuxt: ^4.3.0
    sass-embedded: ^1.97.3
    vue: ^3.5.27
    vue-router: ^5.0.2
  quality:
    '@antfu/eslint-config': ^7.3.0
    '@zinkawaii/stylelint-config': ^0.4.0
    eslint: ^10.0.0
    stylelint: ^17.1.1
  ui:
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/ri': ^1.2.9
    '@nuxt/icon': ^2.2.1
    '@unocss/nuxt': ^66.6.0

engineStrict: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

shamefullyHoist: true
